### ISSUE TITLE
vt normalize v0.5 "Floating point exception (core dumped)" error

### ISSUE THREAD

**Issue by galaxyrise** [atks/vt#10] opened 2015-03-05 00:45 UTC
I just read your excellent variant normalization article and decided to try processing a few of my VCF files.  For a file of INDELs (produced by GATK), I received a "Floating point exception (core dumped)" exception.  For other files, it worked fine.  I wish I could give you something more concrete to troubleshoot, but that was the extent of the error message, and unfortunately I cannot share the variant data due to confidentiality issues.  However, I will see if I can whittle my error-generating file down to check if there is a specific entry causing the exception, and I'll report back if I find anything.

**Comment by galaxyrise** [comment] 2015-03-05 01:24
This is the VCF INDEL entry that is causing the exception:

2       118851381       .       TGAAGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGATGATGATGAT   TGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGATGATGATGAT,T

**Comment by atks** [comment] 2015-03-05 02:01
Hi,

I just tried running on a VCF file with just that entry, and it worked fine returning:

2	118851371	.	TTGATGATGATGAAGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGA	TTGATGATGATGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGA,T	.	.	OLD_VARIANT=2:118851381:TGAAGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGATGATGATGAT/TGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGATGATGATGAT/T

Is there anyway you can link me to a VCF file that reproduces that error which does not contain confidential information?

I'm using htslib which is sensitive to non conforming VCF files, usually GATK VCFs are golden, can you try running the VCf file through vcf-validator from vcftools ?

**Comment by atks** [comment] 2015-03-05 02:37
Can you try running normalize with the option -w 0?  This will prevent the local sorting of the variants, and also turn on the switch -d to print the variant by line so that it is easier to pinpoint the variant that causes the problem.  This will check if the issue is caused by the local sorting mechanism.

Please do a git pull, as the -d option is something that I just added.

**Comment by galaxyrise** [comment] 2015-03-05 03:17
Hi,

Thanks so much for looking into this. I will do your suggested tests at
some point tomorrow. I'll also try to put together an example with the full
record since it must have something to do with either the header or the
fields that I trimmed off in the example that I gave you.

Regards,
Oliver

**Comment by galaxyrise** [comment] 2015-03-05 16:50
Hello,

I haven't done the specific tests you suggested above, but I think I have
the problem narrowed down sufficiently that you should hopefully be able to
reproduce and fix.  I whittled down the single problematic record to a
completely bare-bones VCF file (pasted below).  It results in the floating
point exception.  However, if I simply remove the very last 'T' in the REF
allele it runs without crashing.  Hopefully you can reproduce this same
behavior.

Regards,
Oliver

##fileformat=VCFv4.1
##contig=<ID=2,length=243199373,assembly=b37>
##reference=file:///mypath/human_g1k_v37_decoy.fasta
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT
2 118851381 .
TGAAGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGATGATGATGAT
T 13388.23 . . .

**Comment by atks** [comment] 2015-03-05 16:52
Can you email me the VCF file?  atks@umich.edu.

It will be good if you can point me the reference genome file you are using too.

**Comment by galaxyrise** [comment] 2015-03-05 17:04
Hello,

See below for output with debug mode enabled.  The first attempt is on the
record that causes the crash, and the second is on the record with the last
base of the REF allele trimmed.

Regards,
Oliver


$ vt normalize -d -w 0 -r human_g1k_v37_decoy.fasta -o test_vt.vcf bug.vcf
normalize v0.5

options:     input VCF file        bug.vcf
         [o] output VCF file       test_vt.vcf
         [w] sorting window size   0
         [q] quiet                 false
         [d] debug                 true
         [r] reference FASTA file  human_g1k_v37_decoy.fasta

2:118851381:TGAAGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGATGATGATGAT/T
Floating point exception (core dumped)

$ vt normalize -d -w 0 -r human_g1k_v37_decoy.fasta -o test_vt.vcf
bug_minusT.vcf
normalize v0.5

options:     input VCF file        bug_minusT.vcf
         [o] output VCF file       test_vt.vcf
         [w] sorting window size   0
         [q] quiet                 false
         [d] debug                 true
         [r] reference FASTA file  human_g1k_v37_decoy.fasta

2:118851381:TGAAGGAGAGTTCTGTAGCTACTGAACCTTGCTGAAAGCAACCAGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCTAAAAGCAACCAGATGATGATGATGATGATGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGTTCTGTAGCTACTGAACCTTGCCAAAAGCAACCAGATGATGATGATGATGATGATGATGATGATGATGATGA/T

stats: biallelic
          no. left trimmed                      : 0
          no. right trimmed                     : 0
          no. left and right trimmed            : 0
          no. right trimmed and left aligned    : 0
          no. left aligned                      : 0

       total no. biallelic normalized           : 0

       multiallelic
          no. left trimmed                      : 0
          no. right trimmed                     : 0
          no. left and right trimmed            : 0
          no. right trimmed and left aligned    : 0
          no. left aligned                      : 0

       total no. multiallelic normalized        : 0

       total no. variants normalized            : 0
       total no. variants observed              : 1

Time elapsed: 0.00s

**Comment by atks** [comment] 2015-03-05 17:10
I still cannot reproduce the error.  Can you attach your VCF in an email to me?

**Comment by atks** [comment] 2015-03-05 17:13
Can you also run the following command?

vt validate test.vcf -r human_g1k_v37_decoy.fasta

This will check to make sure if the reference bases are consistent between your vcf and fasta file.

**Comment by atks** [comment] 2015-03-05 17:36
just a summary to close this issue.  apparently, the index file (.fai) for the fasta file was outdated.  The solution was to delete it and allow htslib that is used by vt to reconstruct an updated index that works correctly.

**Closed by atks** 2015-03-05 17:36 UTC

**Comment by spz1st** [comment] 2020-08-18 16:47
Hello, I'm having the same issue and end up here.  Should I create a new issue?  I have my test files available for you to check out.

**Comment by ESDeutekom** [comment] 2025-02-17 15:24
I have the same issue (few years later). The command vt validate throws the name core dump error. I tried removing the .fai file, vt made a new one, but it gave me the same error. Only when the del AATG/A is reached.

Also tried -w 0. 

normalize v0.5

options:     input VCF file                                  dv_filtered_decomp.vcf
         [o] output VCF file                                 dv_filtered_decomp_norm.vcf
         [w] sorting window size                             10000
         [n] no fail on reference inconsistency for non SNPs false
         [q] quiet                                           false
         [d] debug                                           true
         [r] reference FASTA file                            /mnt/db/reference_genomes/homo_sapiens/DRAGEN/Homo_sapiens_assembly38_masked.fasta

chr1:13684:C/T
chr1:13813:T/G
chr1:13838:C/T
chr1:14653:C/T
chr1:14907:A/G
chr1:14930:A/G
chr1:15118:A/G
chr1:15211:T/G
chr1:16378:T/C
chr1:16495:G/C
chr1:16949:A/C
chr1:17385:G/A
chr1:17407:G/A
chr1:30548:T/G
chr1:30923:G/T
chr1:109488:G/A
chr1:124855:A/G
chr1:129010:AATG/A
/.lsbatch/1739805563.4255437: line 8: 2866095 Floating point exception (core dumped) vt normalize -d -r Homo_sapiens_assembly38_masked.fasta -o dv_filtered_decomp_norm.vcf dv_filtered_decomp.vcf
